ALTER TABLE user_account ADD COLUMN IF NOT EXISTS enabled boolean DEFAULT TRUE;

ALTER TABLE user_account ADD COLUMN IF NOT EXISTS password CHARACTER VARYING (255);

ALTER TABLE user_account ADD COLUMN IF NOT EXISTS username CHARACTER VARYING (255);